### ISSUE TITLE
About speaker embedding

### ISSUE THREAD

**Issue by Charlottecuc** [jaywalnut310/glow-tts#10]
Hi. Could you please give me some advice on adding speaker embedding (as you mentioned in the paper) to your code? Thanks!

**Comment by Charlottecuc** [comment]
I mean, how to use the TextMelSpeakerLoader? Thanks

**Comment by Charlottecuc** [comment]
Ah, I see your reply in https://github.com/jaywalnut310/glow-tts/issues/4. 
Thank you very much for your work :)
Besides, could you please tell me how many epochs do we need for the demo model (the LJ dataset) to converge? Thanks!

**Comment by jaywalnut310** [comment]
Thanks for your interest!
The number of training steps of the single speaker model was 240K.
