### ISSUE TITLE
Gradient overflow and negative loss

### ISSUE THREAD

**Issue by Charlottecuc** [jaywalnut310/glow-tts#15]
Hi. I tried to train the model by using a 24-hour mandarin dataset and encountered the following gradient overflow and negative loss problem. 
![Screenshot 2020-06-11 at 2 38 40 PM](https://user-images.githubusercontent.com/43811904/84353385-a3b15f80-abf1-11ea-823c-532e7a11b8b7.png)
![Screenshot 2020-06-11 at 2 38 34 PM](https://user-images.githubusercontent.com/43811904/84353390-a4e28c80-abf1-11ea-9cb2-1f1e039a4bb7.png)
![Screenshot 2020-06-11 at 2 44 01 PM](https://user-images.githubusercontent.com/43811904/84353632-1c182080-abf2-11ea-8d87-cbac5efc636b.png)
![Screenshot 2020-06-11 at 2 44 20 PM](https://user-images.githubusercontent.com/43811904/84353648-1f131100-abf2-11ea-8a68-a91d74575e81.png)
![Screenshot 2020-06-11 at 2 44 28 PM](https://user-images.githubusercontent.com/43811904/84353654-21756b00-abf2-11ea-8706-0cee6ed70158.png)
![Screenshot 2020-06-11 at 2 44 39 PM](https://user-images.githubusercontent.com/43811904/84353660-233f2e80-abf2-11ea-8dc4-93da576666f5.png)

I only changed the "data" part of the config file and modified the "text" folder (cmudict.py, & symbols.py by adding some mandarn phonemes
![Screenshot 2020-06-11 at 2 47 09 PM](https://user-images.githubusercontent.com/43811904/84353847-73b68c00-abf2-11ea-824d-4e5d6ac01894.png)
):
![Screenshot 2020-06-11 at 2 42 45 PM](https://user-images.githubusercontent.com/43811904/84353542-f25ef980-abf1-11ea-8e2e-1138508cc970.png)

Could you give me any suggestion? Thank you!

**Comment by Charlottecuc** [comment]
Besides, I successfully trained the model by using the LJ dataset and the synthezised voice is quite well. 
I also noticed that during the training process, the l_mle_normal is negative:
![Screenshot 2020-06-11 at 5 40 10 PM](https://user-images.githubusercontent.com/43811904/84370334-aff5e680-ac0a-11ea-86ae-1e7b74414b25.png)
![Screenshot 2020-06-11 at 5 42 30 PM](https://user-images.githubusercontent.com/43811904/84370586-08c57f00-ac0b-11ea-836f-4c1908502cf9.png)


My question is, why the loss will become negative?

Thank you!

**Comment by ElijhaLee** [comment]
I think the negative loss is normal, since the loss is log- scalar, which can be negative.

However, I encountered another issue that the grad_norm is larger than you (starting from ~50 and decrease to ~5, then increase to ~10), while it seems that your grad norm is always ~1.

**Comment by anonymous-repo-tech** [comment]
@Charlottecuc Yes, the negative loss is normal, as it stans for negative log-likelihood of data. If you encounter NAN loss, I have no perfect solution, but I can give you a suggestion.

You can change configs `add_noise` to false, and `fp16_run` to false. Switching on/off theses configs may help to increase numerical stability.

**Comment by jaywalnut310** [comment]
@Charlottecuc Yes, the negative loss is normal, as it stans for negative log-likelihood of data. If you encounter NAN loss, I have no perfect solution, but I can give you a suggestion.

You can change configs `add_noise` to false, and `fp16_run` to false. Switching on/off theses configs may help to increase numerical stability.

**Comment by Charlottecuc** [comment]
@jaywalnut310 Hi. I changed `add_noise`to false and it seems that the model is more stable than before. Besides, after changing the "add_noise" to false, do I also need to change the value of "noise_scale" in the inference time? Thanks!

**Comment by jaywalnut310** [comment]
`add_noise` is about whether to add noise in the input data or not. It is not related with `noise_scale`. At inference time, you can change `noise_scale` between 0 to 1 for finding best sample quality.
