### ISSUE TITLE
Why putting a blank token between any two input tokens can improve pronunciation?

### ISSUE THREAD

**Issue by shahuzi** [jaywalnut310/glow-tts#43]
Hi, glow-tts is really a wonderful work! I noticed that your updating in README.md

> 1) moving to a vocoder, HiFi-GAN to reduce noise, 2) putting a blank token between any two input tokens to improve pronunciation

I experimented in Chinese, and the results suggested that add a blank token do improve pronunciation in Chinese. So, **my question is why this trick can improve the pronunciation? Is there any theoretical basis？**

My personal intuition is that this trick can extend the pronunciation time of each phoneme, thereby improving the pronunciation.

Thanks! @jaywalnut310

**Comment by jaywalnut310** [comment]
HI, @shahuzi 

Thanks for your thought. By the way, there is no theoretical basis. Empirically, we found the pronunciation of Glow-TTS between phonemes/characters is sometimes blurry. Thus, we just append blank tokens to represent the shift of pronunciation or the shift of input tokens.

**Comment by shahuzi** [comment]
> HI, @shahuzi
> 
> Thanks for your thought. By the way, there is no theoretical basis. Empirically, we found the pronunciation of Glow-TTS between phonemes/characters is sometimes blurry. Thus, we just append blank tokens to represent the shift of pronunciation or the shift of input tokens.

Fine, Thank you! And, again it's a brilliant work.

**Comment by Liujingxiu23** [comment]
@shahuzi  Hi, I also experimented in Chinese, do you have any conclusion about adding blank between chinese phones?  Is this tick also help the performance of Chinese?

**Comment by shahuzi** [comment]
> @shahuzi Hi, I also experimented in Chinese, do you have any conclusion about adding blank between chinese phones? Is this tick also help the performance of Chinese?

Yes, it is.

**Comment by BridgetteSong** [comment]
> > @shahuzi Hi, I also experimented in Chinese, do you have any conclusion about adding blank between chinese phones? Is this tick also help the performance of Chinese?
> 
> Yes, it is.

I trained in Chinese and added blank between any two phones, but got many wrong pronunciation of tones. but same input types in other models got normal results.

**Comment by hdmjdp** [comment]
> phonemes/characters

I also have this problem, have you solved it?

**Comment by candlewill** [comment]
The computational complexity of the text encoder would increase nearly two times if blank tokens are used. That's why I want to disable it.
