### ISSUE TITLE
Parallelization and GPU requirements

### ISSUE THREAD

**Issue by patdflynn** [jaywalnut310/glow-tts#51]
I see GTTS was developed to be parallelizable. Does training work on let's say several 2080 ti or 3080 rtx?

**Comment by echelon** [comment]
I trained it on LambdaLabs' 8x V100 instances and saw massive speedup, so you should be fine. :)

**Comment by v-nhandt21** [comment]
> I trained it on LambdaLabs' 8x V100 instances and saw massive speedup, so you should be fine. :)

How can I train with Multi-GPU, Do all I need to do is "CUDA_VISIBLE_DEVICES=0,1" and any specific script, can you teach me?
