### ISSUE TITLE
How about the intelligibility and stability

### ISSUE THREAD

**Issue by chazo1994** [jaywalnut310/glow-tts#8]
I read your paper and found that your model have a significant improvement of inference speed, long sentence and character error rate, But I would like to know your experiment about other aspect of intelligibility and stability, how about the misalignment (even you won't use attention), punctuation misalignment, skip word,  worse sound at the end of the long sentence, the stability of long paragraph (like difference voice between two or more sentence of paragraph), etc,... Thank for your hard work!

**Comment by jaywalnut310** [comment]
If what you mean is Attention error analysis as in Robustness section of FastSpeech,
I listed the result in Appendix B. I hope the answer be helpful.
